name: computorticle
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - scikit-learn
  - nilearn
  - pandas
  - r-base=3.6.3
  - r-codetools
  - r-remotes
  - r-reticulate
  - r-rcpp
  - r-rcpparmadillo
  - r-rmarkdown
  - r-tidyverse

